spring:
  flyway:
    enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/digital_document
    username: sa
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: digital_document
