spring:
  application:
    name: prueba-back-web-digital-document

# Actuator endpoints configuration
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: [ info, health, metrics, prometheus ]


outbox:
  topic:
    employee-digital-document: ${KAFKA_TOPIC_OUTPUT:thirdparty.employee.employeedigitaldocument.event.restrictedout.v0.table.cpd}

server:
  port: 8080
